"""Add link_url and image_url to Message model

Revision ID: e03982d55304
Revises: 4e2b1d487a80
Create Date: 2025-06-26 11:01:09.554715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03982d55304'
down_revision = '4e2b1d487a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
